### ISSUE TITLE
please add custom character models

### ISSUE THREAD

**Issue by thesneeder** [NachoToast/SudoCluedo#13]
![among-us-twerk](https://user-images.githubusercontent.com/83119197/158135642-07360aba-8e5a-41eb-95bd-ec653fda38a4.gif)

**Comment by Dakskihedron** [comment]
Add some bitches.

**Comment by Dakskihedron** [comment]
![Fq3zG_5WwAMztD2](https://user-images.githubusercontent.com/47210659/228830746-74f2219e-33a7-4498-87f1-70de6238bead.png)
Fixed
